modules:
  - changed-files:
      - any-glob-to-any-file: libs/**/modules/**

tests:
  - changed-files:
      - any-glob-to-any-file: libs/**/tests/**

examples:
  - changed-files:
      - any-glob-to-any-file: libs/**/examples/**

docs:
  - changed-files:
      - any-glob-to-any-file:
          - libs/**/docs/**
          - '**/*.md'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
          - scripts/**
          - cmake/**
          - .pre-commit-config.yaml

build:
  - changed-files:
      - any-glob-to-any-file:
          - CMakeLists.txt
          - libs/**/CMakeLists.txt
          - cmake/**
          - .clang-format
          - .clangd

type-list:
  - changed-files:
      - any-glob-to-any-file: libs/type-list/**
